// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: bountyhuntersgovernment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWantedPiratesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWantedPiratesRequest) Reset() {
	*x = GetWantedPiratesRequest{}
	mi := &file_bountyhuntersgovernment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWantedPiratesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWantedPiratesRequest) ProtoMessage() {}

func (x *GetWantedPiratesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersgovernment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWantedPiratesRequest.ProtoReflect.Descriptor instead.
func (*GetWantedPiratesRequest) Descriptor() ([]byte, []int) {
	return file_bountyhuntersgovernment_proto_rawDescGZIP(), []int{0}
}

type GetWantedPiratesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pirates       []*Pirate              `protobuf:"bytes,1,rep,name=pirates,proto3" json:"pirates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWantedPiratesResponse) Reset() {
	*x = GetWantedPiratesResponse{}
	mi := &file_bountyhuntersgovernment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWantedPiratesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWantedPiratesResponse) ProtoMessage() {}

func (x *GetWantedPiratesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersgovernment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWantedPiratesResponse.ProtoReflect.Descriptor instead.
func (*GetWantedPiratesResponse) Descriptor() ([]byte, []int) {
	return file_bountyhuntersgovernment_proto_rawDescGZIP(), []int{1}
}

func (x *GetWantedPiratesResponse) GetPirates() []*Pirate {
	if x != nil {
		return x.Pirates
	}
	return nil
}

type SendCaptureReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BountyhunterId int32                  `protobuf:"varint,1,opt,name=BountyhunterId,proto3" json:"BountyhunterId,omitempty"`
	Pirate         *Pirate                `protobuf:"bytes,2,opt,name=Pirate,proto3" json:"Pirate,omitempty"`
	State          string                 `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"` // "Entregado" o "Perdido"
	Buyer          string                 `protobuf:"bytes,4,opt,name=Buyer,proto3" json:"Buyer,omitempty"` // "Marina" o "Submundo"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendCaptureReportRequest) Reset() {
	*x = SendCaptureReportRequest{}
	mi := &file_bountyhuntersgovernment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCaptureReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCaptureReportRequest) ProtoMessage() {}

func (x *SendCaptureReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersgovernment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCaptureReportRequest.ProtoReflect.Descriptor instead.
func (*SendCaptureReportRequest) Descriptor() ([]byte, []int) {
	return file_bountyhuntersgovernment_proto_rawDescGZIP(), []int{2}
}

func (x *SendCaptureReportRequest) GetBountyhunterId() int32 {
	if x != nil {
		return x.BountyhunterId
	}
	return 0
}

func (x *SendCaptureReportRequest) GetPirate() *Pirate {
	if x != nil {
		return x.Pirate
	}
	return nil
}

func (x *SendCaptureReportRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SendCaptureReportRequest) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

type SendCaptureReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewReputation int32                  `protobuf:"varint,1,opt,name=NewReputation,proto3" json:"NewReputation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCaptureReportResponse) Reset() {
	*x = SendCaptureReportResponse{}
	mi := &file_bountyhuntersgovernment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCaptureReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCaptureReportResponse) ProtoMessage() {}

func (x *SendCaptureReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersgovernment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCaptureReportResponse.ProtoReflect.Descriptor instead.
func (*SendCaptureReportResponse) Descriptor() ([]byte, []int) {
	return file_bountyhuntersgovernment_proto_rawDescGZIP(), []int{3}
}

func (x *SendCaptureReportResponse) GetNewReputation() int32 {
	if x != nil {
		return x.NewReputation
	}
	return 0
}

type AssignBountyhunterIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignBountyhunterIdRequest) Reset() {
	*x = AssignBountyhunterIdRequest{}
	mi := &file_bountyhuntersgovernment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignBountyhunterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBountyhunterIdRequest) ProtoMessage() {}

func (x *AssignBountyhunterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersgovernment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBountyhunterIdRequest.ProtoReflect.Descriptor instead.
func (*AssignBountyhunterIdRequest) Descriptor() ([]byte, []int) {
	return file_bountyhuntersgovernment_proto_rawDescGZIP(), []int{4}
}

type AssignBountyhunterIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BountyhunterId int32                  `protobuf:"varint,1,opt,name=BountyhunterId,proto3" json:"BountyhunterId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignBountyhunterIdResponse) Reset() {
	*x = AssignBountyhunterIdResponse{}
	mi := &file_bountyhuntersgovernment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignBountyhunterIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBountyhunterIdResponse) ProtoMessage() {}

func (x *AssignBountyhunterIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersgovernment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBountyhunterIdResponse.ProtoReflect.Descriptor instead.
func (*AssignBountyhunterIdResponse) Descriptor() ([]byte, []int) {
	return file_bountyhuntersgovernment_proto_rawDescGZIP(), []int{5}
}

func (x *AssignBountyhunterIdResponse) GetBountyhunterId() int32 {
	if x != nil {
		return x.BountyhunterId
	}
	return 0
}

var File_bountyhuntersgovernment_proto protoreflect.FileDescriptor

const file_bountyhuntersgovernment_proto_rawDesc = "" +
	"\n" +
	"\x1dbountyhuntersgovernment.proto\x12\x17bountyhuntersgovernment\x1a\fshared.proto\"\x19\n" +
	"\x17GetWantedPiratesRequest\"D\n" +
	"\x18GetWantedPiratesResponse\x12(\n" +
	"\apirates\x18\x01 \x03(\v2\x0e.shared.PirateR\apirates\"\x96\x01\n" +
	"\x18SendCaptureReportRequest\x12&\n" +
	"\x0eBountyhunterId\x18\x01 \x01(\x05R\x0eBountyhunterId\x12&\n" +
	"\x06Pirate\x18\x02 \x01(\v2\x0e.shared.PirateR\x06Pirate\x12\x14\n" +
	"\x05State\x18\x03 \x01(\tR\x05State\x12\x14\n" +
	"\x05Buyer\x18\x04 \x01(\tR\x05Buyer\"A\n" +
	"\x19SendCaptureReportResponse\x12$\n" +
	"\rNewReputation\x18\x01 \x01(\x05R\rNewReputation\"\x1d\n" +
	"\x1bAssignBountyhunterIdRequest\"F\n" +
	"\x1cAssignBountyhunterIdResponse\x12&\n" +
	"\x0eBountyhunterId\x18\x01 \x01(\x05R\x0eBountyhunterId2\x9a\x03\n" +
	"\x17Bountyhuntersgovernment\x12y\n" +
	"\x10GetWantedPirates\x120.bountyhuntersgovernment.GetWantedPiratesRequest\x1a1.bountyhuntersgovernment.GetWantedPiratesResponse\"\x00\x12|\n" +
	"\x11SendCaptureReport\x121.bountyhuntersgovernment.SendCaptureReportRequest\x1a2.bountyhuntersgovernment.SendCaptureReportResponse\"\x00\x12\x85\x01\n" +
	"\x14AssignBountyhunterId\x124.bountyhuntersgovernment.AssignBountyhunterIdRequest\x1a5.bountyhuntersgovernment.AssignBountyhunterIdResponse\"\x00B\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_bountyhuntersgovernment_proto_rawDescOnce sync.Once
	file_bountyhuntersgovernment_proto_rawDescData []byte
)

func file_bountyhuntersgovernment_proto_rawDescGZIP() []byte {
	file_bountyhuntersgovernment_proto_rawDescOnce.Do(func() {
		file_bountyhuntersgovernment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bountyhuntersgovernment_proto_rawDesc), len(file_bountyhuntersgovernment_proto_rawDesc)))
	})
	return file_bountyhuntersgovernment_proto_rawDescData
}

var file_bountyhuntersgovernment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bountyhuntersgovernment_proto_goTypes = []any{
	(*GetWantedPiratesRequest)(nil),      // 0: bountyhuntersgovernment.GetWantedPiratesRequest
	(*GetWantedPiratesResponse)(nil),     // 1: bountyhuntersgovernment.GetWantedPiratesResponse
	(*SendCaptureReportRequest)(nil),     // 2: bountyhuntersgovernment.SendCaptureReportRequest
	(*SendCaptureReportResponse)(nil),    // 3: bountyhuntersgovernment.SendCaptureReportResponse
	(*AssignBountyhunterIdRequest)(nil),  // 4: bountyhuntersgovernment.AssignBountyhunterIdRequest
	(*AssignBountyhunterIdResponse)(nil), // 5: bountyhuntersgovernment.AssignBountyhunterIdResponse
	(*Pirate)(nil),                       // 6: shared.Pirate
}
var file_bountyhuntersgovernment_proto_depIdxs = []int32{
	6, // 0: bountyhuntersgovernment.GetWantedPiratesResponse.pirates:type_name -> shared.Pirate
	6, // 1: bountyhuntersgovernment.SendCaptureReportRequest.Pirate:type_name -> shared.Pirate
	0, // 2: bountyhuntersgovernment.Bountyhuntersgovernment.GetWantedPirates:input_type -> bountyhuntersgovernment.GetWantedPiratesRequest
	2, // 3: bountyhuntersgovernment.Bountyhuntersgovernment.SendCaptureReport:input_type -> bountyhuntersgovernment.SendCaptureReportRequest
	4, // 4: bountyhuntersgovernment.Bountyhuntersgovernment.AssignBountyhunterId:input_type -> bountyhuntersgovernment.AssignBountyhunterIdRequest
	1, // 5: bountyhuntersgovernment.Bountyhuntersgovernment.GetWantedPirates:output_type -> bountyhuntersgovernment.GetWantedPiratesResponse
	3, // 6: bountyhuntersgovernment.Bountyhuntersgovernment.SendCaptureReport:output_type -> bountyhuntersgovernment.SendCaptureReportResponse
	5, // 7: bountyhuntersgovernment.Bountyhuntersgovernment.AssignBountyhunterId:output_type -> bountyhuntersgovernment.AssignBountyhunterIdResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bountyhuntersgovernment_proto_init() }
func file_bountyhuntersgovernment_proto_init() {
	if File_bountyhuntersgovernment_proto != nil {
		return
	}
	file_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bountyhuntersgovernment_proto_rawDesc), len(file_bountyhuntersgovernment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bountyhuntersgovernment_proto_goTypes,
		DependencyIndexes: file_bountyhuntersgovernment_proto_depIdxs,
		MessageInfos:      file_bountyhuntersgovernment_proto_msgTypes,
	}.Build()
	File_bountyhuntersgovernment_proto = out.File
	file_bountyhuntersgovernment_proto_goTypes = nil
	file_bountyhuntersgovernment_proto_depIdxs = nil
}
