// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: bountyhuntersunderworld.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SellUnderworldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pirate        *Pirate                `protobuf:"bytes,1,opt,name=pirate,proto3" json:"pirate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellUnderworldRequest) Reset() {
	*x = SellUnderworldRequest{}
	mi := &file_bountyhuntersunderworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellUnderworldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellUnderworldRequest) ProtoMessage() {}

func (x *SellUnderworldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersunderworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellUnderworldRequest.ProtoReflect.Descriptor instead.
func (*SellUnderworldRequest) Descriptor() ([]byte, []int) {
	return file_bountyhuntersunderworld_proto_rawDescGZIP(), []int{0}
}

func (x *SellUnderworldRequest) GetPirate() *Pirate {
	if x != nil {
		return x.Pirate
	}
	return nil
}

type SellUnderworldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       int64                  `protobuf:"varint,2,opt,name=payment,proto3" json:"payment,omitempty"`
	IsFraud       bool                   `protobuf:"varint,3,opt,name=isFraud,proto3" json:"isFraud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellUnderworldResponse) Reset() {
	*x = SellUnderworldResponse{}
	mi := &file_bountyhuntersunderworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellUnderworldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellUnderworldResponse) ProtoMessage() {}

func (x *SellUnderworldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersunderworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellUnderworldResponse.ProtoReflect.Descriptor instead.
func (*SellUnderworldResponse) Descriptor() ([]byte, []int) {
	return file_bountyhuntersunderworld_proto_rawDescGZIP(), []int{1}
}

func (x *SellUnderworldResponse) GetPayment() int64 {
	if x != nil {
		return x.Payment
	}
	return 0
}

func (x *SellUnderworldResponse) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

type PirateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PirateCatched *Pirate                `protobuf:"bytes,1,opt,name=pirateCatched,proto3" json:"pirateCatched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PirateRequest) Reset() {
	*x = PirateRequest{}
	mi := &file_bountyhuntersunderworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirateRequest) ProtoMessage() {}

func (x *PirateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersunderworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirateRequest.ProtoReflect.Descriptor instead.
func (*PirateRequest) Descriptor() ([]byte, []int) {
	return file_bountyhuntersunderworld_proto_rawDescGZIP(), []int{2}
}

func (x *PirateRequest) GetPirateCatched() *Pirate {
	if x != nil {
		return x.PirateCatched
	}
	return nil
}

type SendingMercenariesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IsSendingMercenaries bool                   `protobuf:"varint,1,opt,name=isSendingMercenaries,proto3" json:"isSendingMercenaries,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SendingMercenariesResponse) Reset() {
	*x = SendingMercenariesResponse{}
	mi := &file_bountyhuntersunderworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendingMercenariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendingMercenariesResponse) ProtoMessage() {}

func (x *SendingMercenariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bountyhuntersunderworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendingMercenariesResponse.ProtoReflect.Descriptor instead.
func (*SendingMercenariesResponse) Descriptor() ([]byte, []int) {
	return file_bountyhuntersunderworld_proto_rawDescGZIP(), []int{3}
}

func (x *SendingMercenariesResponse) GetIsSendingMercenaries() bool {
	if x != nil {
		return x.IsSendingMercenaries
	}
	return false
}

var File_bountyhuntersunderworld_proto protoreflect.FileDescriptor

const file_bountyhuntersunderworld_proto_rawDesc = "" +
	"\n" +
	"\x1dbountyhuntersunderworld.proto\x12\x17bountyhuntersunderworld\x1a\fshared.proto\"?\n" +
	"\x15SellUnderworldRequest\x12&\n" +
	"\x06pirate\x18\x01 \x01(\v2\x0e.shared.PirateR\x06pirate\"L\n" +
	"\x16SellUnderworldResponse\x12\x18\n" +
	"\apayment\x18\x02 \x01(\x03R\apayment\x12\x18\n" +
	"\aisFraud\x18\x03 \x01(\bR\aisFraud\"E\n" +
	"\rPirateRequest\x124\n" +
	"\rpirateCatched\x18\x01 \x01(\v2\x0e.shared.PirateR\rpirateCatched\"P\n" +
	"\x1aSendingMercenariesResponse\x122\n" +
	"\x14isSendingMercenaries\x18\x01 \x01(\bR\x14isSendingMercenaries2\x92\x02\n" +
	"\x1eBountyhuntersUnderworldService\x12o\n" +
	"\n" +
	"SellPirate\x12..bountyhuntersunderworld.SellUnderworldRequest\x1a/.bountyhuntersunderworld.SellUnderworldResponse\"\x00\x12\x7f\n" +
	"\x1eIsUnderworldSendingMercenaries\x12&.bountyhuntersunderworld.PirateRequest\x1a3.bountyhuntersunderworld.SendingMercenariesResponse\"\x00B\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_bountyhuntersunderworld_proto_rawDescOnce sync.Once
	file_bountyhuntersunderworld_proto_rawDescData []byte
)

func file_bountyhuntersunderworld_proto_rawDescGZIP() []byte {
	file_bountyhuntersunderworld_proto_rawDescOnce.Do(func() {
		file_bountyhuntersunderworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bountyhuntersunderworld_proto_rawDesc), len(file_bountyhuntersunderworld_proto_rawDesc)))
	})
	return file_bountyhuntersunderworld_proto_rawDescData
}

var file_bountyhuntersunderworld_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bountyhuntersunderworld_proto_goTypes = []any{
	(*SellUnderworldRequest)(nil),      // 0: bountyhuntersunderworld.SellUnderworldRequest
	(*SellUnderworldResponse)(nil),     // 1: bountyhuntersunderworld.SellUnderworldResponse
	(*PirateRequest)(nil),              // 2: bountyhuntersunderworld.PirateRequest
	(*SendingMercenariesResponse)(nil), // 3: bountyhuntersunderworld.SendingMercenariesResponse
	(*Pirate)(nil),                     // 4: shared.Pirate
}
var file_bountyhuntersunderworld_proto_depIdxs = []int32{
	4, // 0: bountyhuntersunderworld.SellUnderworldRequest.pirate:type_name -> shared.Pirate
	4, // 1: bountyhuntersunderworld.PirateRequest.pirateCatched:type_name -> shared.Pirate
	0, // 2: bountyhuntersunderworld.BountyhuntersUnderworldService.SellPirate:input_type -> bountyhuntersunderworld.SellUnderworldRequest
	2, // 3: bountyhuntersunderworld.BountyhuntersUnderworldService.IsUnderworldSendingMercenaries:input_type -> bountyhuntersunderworld.PirateRequest
	1, // 4: bountyhuntersunderworld.BountyhuntersUnderworldService.SellPirate:output_type -> bountyhuntersunderworld.SellUnderworldResponse
	3, // 5: bountyhuntersunderworld.BountyhuntersUnderworldService.IsUnderworldSendingMercenaries:output_type -> bountyhuntersunderworld.SendingMercenariesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bountyhuntersunderworld_proto_init() }
func file_bountyhuntersunderworld_proto_init() {
	if File_bountyhuntersunderworld_proto != nil {
		return
	}
	file_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bountyhuntersunderworld_proto_rawDesc), len(file_bountyhuntersunderworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bountyhuntersunderworld_proto_goTypes,
		DependencyIndexes: file_bountyhuntersunderworld_proto_depIdxs,
		MessageInfos:      file_bountyhuntersunderworld_proto_msgTypes,
	}.Build()
	File_bountyhuntersunderworld_proto = out.File
	file_bountyhuntersunderworld_proto_goTypes = nil
	file_bountyhuntersunderworld_proto_depIdxs = nil
}
