// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/lcp_gimnasios.proto

package compiled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Respuesta opcional del servicio gRPC (puede retornar estado simple o nada)
type CombateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"` // "ok" o mensaje de error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombateResponse) Reset() {
	*x = CombateResponse{}
	mi := &file_proto_lcp_gimnasios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombateResponse) ProtoMessage() {}

func (x *CombateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lcp_gimnasios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombateResponse.ProtoReflect.Descriptor instead.
func (*CombateResponse) Descriptor() ([]byte, []int) {
	return file_proto_lcp_gimnasios_proto_rawDescGZIP(), []int{0}
}

func (x *CombateResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

// Mensaje enviado por LCP al gimnasio para asignar un combate
type CombateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombateId     string                 `protobuf:"bytes,1,opt,name=CombateId,proto3" json:"CombateId,omitempty"` // ID del gimnasio
	TorneoId      int64                  `protobuf:"varint,2,opt,name=TorneoId,proto3" json:"TorneoId,omitempty"`
	Entrenador1   *Entrenador            `protobuf:"bytes,3,opt,name=Entrenador1,proto3" json:"Entrenador1,omitempty"`
	Entrenador2   *Entrenador            `protobuf:"bytes,4,opt,name=Entrenador2,proto3" json:"Entrenador2,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=Region,proto3" json:"Region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombateRequest) Reset() {
	*x = CombateRequest{}
	mi := &file_proto_lcp_gimnasios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombateRequest) ProtoMessage() {}

func (x *CombateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lcp_gimnasios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombateRequest.ProtoReflect.Descriptor instead.
func (*CombateRequest) Descriptor() ([]byte, []int) {
	return file_proto_lcp_gimnasios_proto_rawDescGZIP(), []int{1}
}

func (x *CombateRequest) GetCombateId() string {
	if x != nil {
		return x.CombateId
	}
	return ""
}

func (x *CombateRequest) GetTorneoId() int64 {
	if x != nil {
		return x.TorneoId
	}
	return 0
}

func (x *CombateRequest) GetEntrenador1() *Entrenador {
	if x != nil {
		return x.Entrenador1
	}
	return nil
}

func (x *CombateRequest) GetEntrenador2() *Entrenador {
	if x != nil {
		return x.Entrenador2
	}
	return nil
}

func (x *CombateRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_proto_lcp_gimnasios_proto protoreflect.FileDescriptor

const file_proto_lcp_gimnasios_proto_rawDesc = "" +
	"\n" +
	"\x19proto/lcp_gimnasios.proto\x12\acombate\x1a\x12proto/shared.proto\")\n" +
	"\x0fCombateResponse\x12\x16\n" +
	"\x06Estado\x18\x01 \x01(\tR\x06Estado\"\xce\x01\n" +
	"\x0eCombateRequest\x12\x1c\n" +
	"\tCombateId\x18\x01 \x01(\tR\tCombateId\x12\x1a\n" +
	"\bTorneoId\x18\x02 \x01(\x03R\bTorneoId\x124\n" +
	"\vEntrenador1\x18\x03 \x01(\v2\x12.shared.EntrenadorR\vEntrenador1\x124\n" +
	"\vEntrenador2\x18\x04 \x01(\v2\x12.shared.EntrenadorR\vEntrenador2\x12\x16\n" +
	"\x06Region\x18\a \x01(\tR\x06Region2S\n" +
	"\fLCP_Gimnasio\x12C\n" +
	"\x0eAsignarCombate\x12\x17.combate.CombateRequest\x1a\x18.combate.CombateResponseB\x10Z\x0eproto/compiledb\x06proto3"

var (
	file_proto_lcp_gimnasios_proto_rawDescOnce sync.Once
	file_proto_lcp_gimnasios_proto_rawDescData []byte
)

func file_proto_lcp_gimnasios_proto_rawDescGZIP() []byte {
	file_proto_lcp_gimnasios_proto_rawDescOnce.Do(func() {
		file_proto_lcp_gimnasios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lcp_gimnasios_proto_rawDesc), len(file_proto_lcp_gimnasios_proto_rawDesc)))
	})
	return file_proto_lcp_gimnasios_proto_rawDescData
}

var file_proto_lcp_gimnasios_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lcp_gimnasios_proto_goTypes = []any{
	(*CombateResponse)(nil), // 0: combate.CombateResponse
	(*CombateRequest)(nil),  // 1: combate.CombateRequest
	(*Entrenador)(nil),      // 2: shared.Entrenador
}
var file_proto_lcp_gimnasios_proto_depIdxs = []int32{
	2, // 0: combate.CombateRequest.Entrenador1:type_name -> shared.Entrenador
	2, // 1: combate.CombateRequest.Entrenador2:type_name -> shared.Entrenador
	1, // 2: combate.LCP_Gimnasio.AsignarCombate:input_type -> combate.CombateRequest
	0, // 3: combate.LCP_Gimnasio.AsignarCombate:output_type -> combate.CombateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_lcp_gimnasios_proto_init() }
func file_proto_lcp_gimnasios_proto_init() {
	if File_proto_lcp_gimnasios_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lcp_gimnasios_proto_rawDesc), len(file_proto_lcp_gimnasios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lcp_gimnasios_proto_goTypes,
		DependencyIndexes: file_proto_lcp_gimnasios_proto_depIdxs,
		MessageInfos:      file_proto_lcp_gimnasios_proto_msgTypes,
	}.Build()
	File_proto_lcp_gimnasios_proto = out.File
	file_proto_lcp_gimnasios_proto_goTypes = nil
	file_proto_lcp_gimnasios_proto_depIdxs = nil
}
