// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/lcp_entrenadores.proto

package compiled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entrenador    *Entrenador            `protobuf:"bytes,1,opt,name=Entrenador,proto3" json:"Entrenador,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_lcp_entrenadores_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetEntrenador() *Entrenador {
	if x != nil {
		return x.Entrenador
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torneos       []*Torneo              `protobuf:"bytes,1,rep,name=Torneos,proto3" json:"Torneos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_lcp_entrenadores_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetTorneos() []*Torneo {
	if x != nil {
		return x.Torneos
	}
	return nil
}

type InscripcionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTorneo      int64                  `protobuf:"varint,1,opt,name=IdTorneo,proto3" json:"IdTorneo,omitempty"`
	Entrenador    *Entrenador            `protobuf:"bytes,2,opt,name=Entrenador,proto3" json:"Entrenador,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InscripcionRequest) Reset() {
	*x = InscripcionRequest{}
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionRequest) ProtoMessage() {}

func (x *InscripcionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionRequest.ProtoReflect.Descriptor instead.
func (*InscripcionRequest) Descriptor() ([]byte, []int) {
	return file_proto_lcp_entrenadores_proto_rawDescGZIP(), []int{2}
}

func (x *InscripcionRequest) GetIdTorneo() int64 {
	if x != nil {
		return x.IdTorneo
	}
	return 0
}

func (x *InscripcionRequest) GetEntrenador() *Entrenador {
	if x != nil {
		return x.Entrenador
	}
	return nil
}

type InscripcionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=Mensaje,proto3" json:"Mensaje,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"` // 1: Ok, 2: Torneo no está disponible 3: Región incompatible con el torneo 4: Inscrito en otro torneo 5: Inscrito en este torneo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InscripcionResponse) Reset() {
	*x = InscripcionResponse{}
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionResponse) ProtoMessage() {}

func (x *InscripcionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lcp_entrenadores_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionResponse.ProtoReflect.Descriptor instead.
func (*InscripcionResponse) Descriptor() ([]byte, []int) {
	return file_proto_lcp_entrenadores_proto_rawDescGZIP(), []int{3}
}

func (x *InscripcionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *InscripcionResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_lcp_entrenadores_proto protoreflect.FileDescriptor

const file_proto_lcp_entrenadores_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/lcp_entrenadores.proto\x12\x10lcp_entrenadores\x1a\x12proto/shared.proto\"B\n" +
	"\fQueryRequest\x122\n" +
	"\n" +
	"Entrenador\x18\x01 \x01(\v2\x12.shared.EntrenadorR\n" +
	"Entrenador\"9\n" +
	"\rQueryResponse\x12(\n" +
	"\aTorneos\x18\x01 \x03(\v2\x0e.shared.TorneoR\aTorneos\"d\n" +
	"\x12InscripcionRequest\x12\x1a\n" +
	"\bIdTorneo\x18\x01 \x01(\x03R\bIdTorneo\x122\n" +
	"\n" +
	"Entrenador\x18\x02 \x01(\v2\x12.shared.EntrenadorR\n" +
	"Entrenador\"G\n" +
	"\x13InscripcionResponse\x12\x18\n" +
	"\aMensaje\x18\x01 \x01(\tR\aMensaje\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\x05R\x06Status2\xda\x01\n" +
	"\x10LCP_Entrenadores\x12`\n" +
	"\x1bConsultarTorneosDisponibles\x12\x1e.lcp_entrenadores.QueryRequest\x1a\x1f.lcp_entrenadores.QueryResponse\"\x00\x12d\n" +
	"\x13InscribirEntrenador\x12$.lcp_entrenadores.InscripcionRequest\x1a%.lcp_entrenadores.InscripcionResponse\"\x00B\x10Z\x0eproto/compiledb\x06proto3"

var (
	file_proto_lcp_entrenadores_proto_rawDescOnce sync.Once
	file_proto_lcp_entrenadores_proto_rawDescData []byte
)

func file_proto_lcp_entrenadores_proto_rawDescGZIP() []byte {
	file_proto_lcp_entrenadores_proto_rawDescOnce.Do(func() {
		file_proto_lcp_entrenadores_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lcp_entrenadores_proto_rawDesc), len(file_proto_lcp_entrenadores_proto_rawDesc)))
	})
	return file_proto_lcp_entrenadores_proto_rawDescData
}

var file_proto_lcp_entrenadores_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_lcp_entrenadores_proto_goTypes = []any{
	(*QueryRequest)(nil),        // 0: lcp_entrenadores.QueryRequest
	(*QueryResponse)(nil),       // 1: lcp_entrenadores.QueryResponse
	(*InscripcionRequest)(nil),  // 2: lcp_entrenadores.InscripcionRequest
	(*InscripcionResponse)(nil), // 3: lcp_entrenadores.InscripcionResponse
	(*Entrenador)(nil),          // 4: shared.Entrenador
	(*Torneo)(nil),              // 5: shared.Torneo
}
var file_proto_lcp_entrenadores_proto_depIdxs = []int32{
	4, // 0: lcp_entrenadores.QueryRequest.Entrenador:type_name -> shared.Entrenador
	5, // 1: lcp_entrenadores.QueryResponse.Torneos:type_name -> shared.Torneo
	4, // 2: lcp_entrenadores.InscripcionRequest.Entrenador:type_name -> shared.Entrenador
	0, // 3: lcp_entrenadores.LCP_Entrenadores.ConsultarTorneosDisponibles:input_type -> lcp_entrenadores.QueryRequest
	2, // 4: lcp_entrenadores.LCP_Entrenadores.InscribirEntrenador:input_type -> lcp_entrenadores.InscripcionRequest
	1, // 5: lcp_entrenadores.LCP_Entrenadores.ConsultarTorneosDisponibles:output_type -> lcp_entrenadores.QueryResponse
	3, // 6: lcp_entrenadores.LCP_Entrenadores.InscribirEntrenador:output_type -> lcp_entrenadores.InscripcionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_lcp_entrenadores_proto_init() }
func file_proto_lcp_entrenadores_proto_init() {
	if File_proto_lcp_entrenadores_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lcp_entrenadores_proto_rawDesc), len(file_proto_lcp_entrenadores_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lcp_entrenadores_proto_goTypes,
		DependencyIndexes: file_proto_lcp_entrenadores_proto_depIdxs,
		MessageInfos:      file_proto_lcp_entrenadores_proto_msgTypes,
	}.Build()
	File_proto_lcp_entrenadores_proto = out.File
	file_proto_lcp_entrenadores_proto_goTypes = nil
	file_proto_lcp_entrenadores_proto_depIdxs = nil
}
