// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: proto/lcp_gimnasios.proto

package compiled

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LCP_Gimnasio_AsignarCombate_FullMethodName = "/combate.LCP_Gimnasio/AsignarCombate"
)

// LCP_GimnasioClient is the client API for LCP_Gimnasio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LCP_GimnasioClient interface {
	AsignarCombate(ctx context.Context, in *CombateRequest, opts ...grpc.CallOption) (*CombateResponse, error)
}

type lCP_GimnasioClient struct {
	cc grpc.ClientConnInterface
}

func NewLCP_GimnasioClient(cc grpc.ClientConnInterface) LCP_GimnasioClient {
	return &lCP_GimnasioClient{cc}
}

func (c *lCP_GimnasioClient) AsignarCombate(ctx context.Context, in *CombateRequest, opts ...grpc.CallOption) (*CombateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombateResponse)
	err := c.cc.Invoke(ctx, LCP_Gimnasio_AsignarCombate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LCP_GimnasioServer is the server API for LCP_Gimnasio service.
// All implementations must embed UnimplementedLCP_GimnasioServer
// for forward compatibility.
type LCP_GimnasioServer interface {
	AsignarCombate(context.Context, *CombateRequest) (*CombateResponse, error)
	mustEmbedUnimplementedLCP_GimnasioServer()
}

// UnimplementedLCP_GimnasioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLCP_GimnasioServer struct{}

func (UnimplementedLCP_GimnasioServer) AsignarCombate(context.Context, *CombateRequest) (*CombateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsignarCombate not implemented")
}
func (UnimplementedLCP_GimnasioServer) mustEmbedUnimplementedLCP_GimnasioServer() {}
func (UnimplementedLCP_GimnasioServer) testEmbeddedByValue()                      {}

// UnsafeLCP_GimnasioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LCP_GimnasioServer will
// result in compilation errors.
type UnsafeLCP_GimnasioServer interface {
	mustEmbedUnimplementedLCP_GimnasioServer()
}

func RegisterLCP_GimnasioServer(s grpc.ServiceRegistrar, srv LCP_GimnasioServer) {
	// If the following call pancis, it indicates UnimplementedLCP_GimnasioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LCP_Gimnasio_ServiceDesc, srv)
}

func _LCP_Gimnasio_AsignarCombate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LCP_GimnasioServer).AsignarCombate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LCP_Gimnasio_AsignarCombate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LCP_GimnasioServer).AsignarCombate(ctx, req.(*CombateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LCP_Gimnasio_ServiceDesc is the grpc.ServiceDesc for LCP_Gimnasio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LCP_Gimnasio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "combate.LCP_Gimnasio",
	HandlerType: (*LCP_GimnasioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AsignarCombate",
			Handler:    _LCP_Gimnasio_AsignarCombate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lcp_gimnasios.proto",
}
