// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/shared.proto

package compiled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Torneo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	Inscritos     []*Entrenador          `protobuf:"bytes,3,rep,name=Inscritos,proto3" json:"Inscritos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Torneo) Reset() {
	*x = Torneo{}
	mi := &file_proto_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Torneo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torneo) ProtoMessage() {}

func (x *Torneo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torneo.ProtoReflect.Descriptor instead.
func (*Torneo) Descriptor() ([]byte, []int) {
	return file_proto_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Torneo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Torneo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Torneo) GetInscritos() []*Entrenador {
	if x != nil {
		return x.Inscritos
	}
	return nil
}

type Entrenador struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=Nombre,proto3" json:"Nombre,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=Region,proto3" json:"Region,omitempty"`
	Ranking       int64                  `protobuf:"varint,4,opt,name=Ranking,proto3" json:"Ranking,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=Estado,proto3" json:"Estado,omitempty"`
	Suspendido    int64                  `protobuf:"varint,6,opt,name=Suspendido,proto3" json:"Suspendido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrenador) Reset() {
	*x = Entrenador{}
	mi := &file_proto_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrenador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrenador) ProtoMessage() {}

func (x *Entrenador) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrenador.ProtoReflect.Descriptor instead.
func (*Entrenador) Descriptor() ([]byte, []int) {
	return file_proto_shared_proto_rawDescGZIP(), []int{1}
}

func (x *Entrenador) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entrenador) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Entrenador) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Entrenador) GetRanking() int64 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *Entrenador) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Entrenador) GetSuspendido() int64 {
	if x != nil {
		return x.Suspendido
	}
	return 0
}

var File_proto_shared_proto protoreflect.FileDescriptor

const file_proto_shared_proto_rawDesc = "" +
	"\n" +
	"\x12proto/shared.proto\x12\x06shared\"b\n" +
	"\x06Torneo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06Region\x18\x02 \x01(\tR\x06Region\x120\n" +
	"\tInscritos\x18\x03 \x03(\v2\x12.shared.EntrenadorR\tInscritos\"\x9e\x01\n" +
	"\n" +
	"Entrenador\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Nombre\x18\x02 \x01(\tR\x06Nombre\x12\x16\n" +
	"\x06Region\x18\x03 \x01(\tR\x06Region\x12\x18\n" +
	"\aRanking\x18\x04 \x01(\x03R\aRanking\x12\x16\n" +
	"\x06Estado\x18\x05 \x01(\tR\x06Estado\x12\x1e\n" +
	"\n" +
	"Suspendido\x18\x06 \x01(\x03R\n" +
	"Suspendido2\b\n" +
	"\x06SharedB\x10Z\x0eproto/compiledb\x06proto3"

var (
	file_proto_shared_proto_rawDescOnce sync.Once
	file_proto_shared_proto_rawDescData []byte
)

func file_proto_shared_proto_rawDescGZIP() []byte {
	file_proto_shared_proto_rawDescOnce.Do(func() {
		file_proto_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shared_proto_rawDesc), len(file_proto_shared_proto_rawDesc)))
	})
	return file_proto_shared_proto_rawDescData
}

var file_proto_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_shared_proto_goTypes = []any{
	(*Torneo)(nil),     // 0: shared.Torneo
	(*Entrenador)(nil), // 1: shared.Entrenador
}
var file_proto_shared_proto_depIdxs = []int32{
	1, // 0: shared.Torneo.Inscritos:type_name -> shared.Entrenador
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shared_proto_init() }
func file_proto_shared_proto_init() {
	if File_proto_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shared_proto_rawDesc), len(file_proto_shared_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shared_proto_goTypes,
		DependencyIndexes: file_proto_shared_proto_depIdxs,
		MessageInfos:      file_proto_shared_proto_msgTypes,
	}.Build()
	File_proto_shared_proto = out.File
	file_proto_shared_proto_goTypes = nil
	file_proto_shared_proto_depIdxs = nil
}
