// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/lcp_entrenadores.proto

package compiled

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LCP_Entrenadores_ConsultarTorneosDisponibles_FullMethodName = "/lcp_entrenadores.LCP_Entrenadores/ConsultarTorneosDisponibles"
	LCP_Entrenadores_InscribirEntrenador_FullMethodName         = "/lcp_entrenadores.LCP_Entrenadores/InscribirEntrenador"
)

// LCP_EntrenadoresClient is the client API for LCP_Entrenadores service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio entre LCP y entrenadores
type LCP_EntrenadoresClient interface {
	ConsultarTorneosDisponibles(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	InscribirEntrenador(ctx context.Context, in *InscripcionRequest, opts ...grpc.CallOption) (*InscripcionResponse, error)
}

type lCP_EntrenadoresClient struct {
	cc grpc.ClientConnInterface
}

func NewLCP_EntrenadoresClient(cc grpc.ClientConnInterface) LCP_EntrenadoresClient {
	return &lCP_EntrenadoresClient{cc}
}

func (c *lCP_EntrenadoresClient) ConsultarTorneosDisponibles(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LCP_Entrenadores_ConsultarTorneosDisponibles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lCP_EntrenadoresClient) InscribirEntrenador(ctx context.Context, in *InscripcionRequest, opts ...grpc.CallOption) (*InscripcionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InscripcionResponse)
	err := c.cc.Invoke(ctx, LCP_Entrenadores_InscribirEntrenador_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LCP_EntrenadoresServer is the server API for LCP_Entrenadores service.
// All implementations must embed UnimplementedLCP_EntrenadoresServer
// for forward compatibility.
//
// Servicio entre LCP y entrenadores
type LCP_EntrenadoresServer interface {
	ConsultarTorneosDisponibles(context.Context, *QueryRequest) (*QueryResponse, error)
	InscribirEntrenador(context.Context, *InscripcionRequest) (*InscripcionResponse, error)
	mustEmbedUnimplementedLCP_EntrenadoresServer()
}

// UnimplementedLCP_EntrenadoresServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLCP_EntrenadoresServer struct{}

func (UnimplementedLCP_EntrenadoresServer) ConsultarTorneosDisponibles(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultarTorneosDisponibles not implemented")
}
func (UnimplementedLCP_EntrenadoresServer) InscribirEntrenador(context.Context, *InscripcionRequest) (*InscripcionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InscribirEntrenador not implemented")
}
func (UnimplementedLCP_EntrenadoresServer) mustEmbedUnimplementedLCP_EntrenadoresServer() {}
func (UnimplementedLCP_EntrenadoresServer) testEmbeddedByValue()                          {}

// UnsafeLCP_EntrenadoresServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LCP_EntrenadoresServer will
// result in compilation errors.
type UnsafeLCP_EntrenadoresServer interface {
	mustEmbedUnimplementedLCP_EntrenadoresServer()
}

func RegisterLCP_EntrenadoresServer(s grpc.ServiceRegistrar, srv LCP_EntrenadoresServer) {
	// If the following call pancis, it indicates UnimplementedLCP_EntrenadoresServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LCP_Entrenadores_ServiceDesc, srv)
}

func _LCP_Entrenadores_ConsultarTorneosDisponibles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LCP_EntrenadoresServer).ConsultarTorneosDisponibles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LCP_Entrenadores_ConsultarTorneosDisponibles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LCP_EntrenadoresServer).ConsultarTorneosDisponibles(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LCP_Entrenadores_InscribirEntrenador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InscripcionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LCP_EntrenadoresServer).InscribirEntrenador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LCP_Entrenadores_InscribirEntrenador_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LCP_EntrenadoresServer).InscribirEntrenador(ctx, req.(*InscripcionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LCP_Entrenadores_ServiceDesc is the grpc.ServiceDesc for LCP_Entrenadores service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LCP_Entrenadores_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcp_entrenadores.LCP_Entrenadores",
	HandlerType: (*LCP_EntrenadoresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultarTorneosDisponibles",
			Handler:    _LCP_Entrenadores_ConsultarTorneosDisponibles_Handler,
		},
		{
			MethodName: "InscribirEntrenador",
			Handler:    _LCP_Entrenadores_InscribirEntrenador_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lcp_entrenadores.proto",
}
