// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/shared.proto

package compiled

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// SharedClient is the client API for Shared service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio compartido
type SharedClient interface {
}

type sharedClient struct {
	cc grpc.ClientConnInterface
}

func NewSharedClient(cc grpc.ClientConnInterface) SharedClient {
	return &sharedClient{cc}
}

// SharedServer is the server API for Shared service.
// All implementations must embed UnimplementedSharedServer
// for forward compatibility.
//
// Servicio compartido
type SharedServer interface {
	mustEmbedUnimplementedSharedServer()
}

// UnimplementedSharedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharedServer struct{}

func (UnimplementedSharedServer) mustEmbedUnimplementedSharedServer() {}
func (UnimplementedSharedServer) testEmbeddedByValue()                {}

// UnsafeSharedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharedServer will
// result in compilation errors.
type UnsafeSharedServer interface {
	mustEmbedUnimplementedSharedServer()
}

func RegisterSharedServer(s grpc.ServiceRegistrar, srv SharedServer) {
	// If the following call pancis, it indicates UnimplementedSharedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shared_ServiceDesc, srv)
}

// Shared_ServiceDesc is the grpc.ServiceDesc for Shared service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shared_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shared.Shared",
	HandlerType: (*SharedServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/shared.proto",
}
