docker-gameservers-1:
	docker run --rm -it -p 50055:50055 gameservers 1 50055

docker-gameservers-2:
	docker run --rm -it -p 50056:50056 gameservers 2 50056

docker-gameservers-3:
	docker run --rm -it -p 50057:50057 gameservers 3 50057

docker-build-gameservers:
	docker build -t gameservers .