docker-marina:
	docker compose up --build marine

docker-gobierno:
	docker compose up --build government

docker-cazarrecompensas:
	docker compose up --build bountyhunters

docker-submundo:
	docker compose up --build underworld