services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"    # puerto para conexiones AMQP
      - "15672:15672"
    networks:
      - test_network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  entrenadores:
    build: ./entrenadores
    command: ["./entrenadores","${FILE_NAME}"]
    container_name: entrenadores_container
    networks:
      - test_network
    volumes:
      - ./entrenadores/data:/app/data
  
  lcp:
    build: ./lcp
    container_name: lcp_container
    ports:
      - "50051:50051"
    networks:
      - test_network

  gimnasios:
    build: ./gimnasios-snp/gimnasios
    container_name: gimnasios_container
    ports:
      - "50052:50052"
      - "50053:50053"
      - "50054:50054"
      - "50055:50055"
      - "50056:50056"
    env_file:
      - ./gimnasios-snp/gimnasios/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - test_network
    
  cdp:
    build: ./cdp
    container_name: cdp_container
    env_file:
      - ./cdp/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - test_network
  
  snp:
    build: ./gimnasios-snp/snp
    container_name: snp_container
    ports:
      - "50057:50057"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - test_network

networks:
  test_network:
    external: false