// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/cdp_lcp.proto

package compiled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje de petición: enviamos los dos IDs de los entrenadores
type ValidarEntrenadoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id1           string                 `protobuf:"bytes,1,opt,name=Id1,proto3" json:"Id1,omitempty"`
	Id2           string                 `protobuf:"bytes,2,opt,name=Id2,proto3" json:"Id2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarEntrenadoresRequest) Reset() {
	*x = ValidarEntrenadoresRequest{}
	mi := &file_proto_cdp_lcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarEntrenadoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarEntrenadoresRequest) ProtoMessage() {}

func (x *ValidarEntrenadoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_lcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarEntrenadoresRequest.ProtoReflect.Descriptor instead.
func (*ValidarEntrenadoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_lcp_proto_rawDescGZIP(), []int{0}
}

func (x *ValidarEntrenadoresRequest) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *ValidarEntrenadoresRequest) GetId2() string {
	if x != nil {
		return x.Id2
	}
	return ""
}

// Mensaje de respuesta: indicamos si ambos están activos
type ValidarEntrenadoresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true si **ambos** entrenadores existen y están en estado Activo
	Activos       bool `protobuf:"varint,1,opt,name=Activos,proto3" json:"Activos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarEntrenadoresResponse) Reset() {
	*x = ValidarEntrenadoresResponse{}
	mi := &file_proto_cdp_lcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarEntrenadoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarEntrenadoresResponse) ProtoMessage() {}

func (x *ValidarEntrenadoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_lcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarEntrenadoresResponse.ProtoReflect.Descriptor instead.
func (*ValidarEntrenadoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_lcp_proto_rawDescGZIP(), []int{1}
}

func (x *ValidarEntrenadoresResponse) GetActivos() bool {
	if x != nil {
		return x.Activos
	}
	return false
}

var File_proto_cdp_lcp_proto protoreflect.FileDescriptor

const file_proto_cdp_lcp_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cdp_lcp.proto\x12\acdp_lcp\"@\n" +
	"\x1aValidarEntrenadoresRequest\x12\x10\n" +
	"\x03Id1\x18\x01 \x01(\tR\x03Id1\x12\x10\n" +
	"\x03Id2\x18\x02 \x01(\tR\x03Id2\"7\n" +
	"\x1bValidarEntrenadoresResponse\x12\x18\n" +
	"\aActivos\x18\x01 \x01(\bR\aActivos2k\n" +
	"\aCDP_LCP\x12`\n" +
	"\x13ValidarEntrenadores\x12#.cdp_lcp.ValidarEntrenadoresRequest\x1a$.cdp_lcp.ValidarEntrenadoresResponseB\x10Z\x0eproto/compiledb\x06proto3"

var (
	file_proto_cdp_lcp_proto_rawDescOnce sync.Once
	file_proto_cdp_lcp_proto_rawDescData []byte
)

func file_proto_cdp_lcp_proto_rawDescGZIP() []byte {
	file_proto_cdp_lcp_proto_rawDescOnce.Do(func() {
		file_proto_cdp_lcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_lcp_proto_rawDesc), len(file_proto_cdp_lcp_proto_rawDesc)))
	})
	return file_proto_cdp_lcp_proto_rawDescData
}

var file_proto_cdp_lcp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cdp_lcp_proto_goTypes = []any{
	(*ValidarEntrenadoresRequest)(nil),  // 0: cdp_lcp.ValidarEntrenadoresRequest
	(*ValidarEntrenadoresResponse)(nil), // 1: cdp_lcp.ValidarEntrenadoresResponse
}
var file_proto_cdp_lcp_proto_depIdxs = []int32{
	0, // 0: cdp_lcp.CDP_LCP.ValidarEntrenadores:input_type -> cdp_lcp.ValidarEntrenadoresRequest
	1, // 1: cdp_lcp.CDP_LCP.ValidarEntrenadores:output_type -> cdp_lcp.ValidarEntrenadoresResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cdp_lcp_proto_init() }
func file_proto_cdp_lcp_proto_init() {
	if File_proto_cdp_lcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_lcp_proto_rawDesc), len(file_proto_cdp_lcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_lcp_proto_goTypes,
		DependencyIndexes: file_proto_cdp_lcp_proto_depIdxs,
		MessageInfos:      file_proto_cdp_lcp_proto_msgTypes,
	}.Build()
	File_proto_cdp_lcp_proto = out.File
	file_proto_cdp_lcp_proto_goTypes = nil
	file_proto_cdp_lcp_proto_depIdxs = nil
}
